export const BookingError = {
    COMMON_BOOKING_CREATION_ERROR: 'FAIL TO CREATE THE BOOKING',
    BOOKING_MISSING_SERVICE_INFORMATION_ERROR: 'MISSING SERVICE INFORMATION ATTACHED IN BOOKING',
    STAFF_IS_NOT_AVAILABLE_FOR_CUSTOMER_BOOKING: 'CANNOT BOOK AS THE CHOSEN STAFF IS NOT AVALABLE',
    SERVICE_IS_NOT_EXISTED_FOR_THE_BOOKING: 'MISSING SERVICE INFORMATION IN BOOKING INFORMATION',
    BOOKING_START_TIME_INVALIDATION : 'BOOKING START TIME IS OLDER THEN NOW',
    BOOKING_START_TIME_OVER_30_DAYS_AHEAD: 'CANNOT BOOKING MORE THAN 30 DAYS IN ADVANCE',
    BOOKING_TIME_INPUT_CONFLICTION_ERROR: 'BOOKING START TIME CONFLICTS WITH BOOKING END TIME',
    BOOKING_OVERLAP_SCHEDULE_ERROR: 'THE BOOKING REQUEST IS NOT AVAILABLE AS CHOSEN STAFF IS ATTACHED WITH THE OTHER SAME SCHEDULE INFORMATION'
}