export const BookingError = {
    BOOKING_CREATION_MISSING_SERVICE_INFORMATION: "MISSING SERVICE INFORMATION",
    BOOKING_CREATION_MISSING_CUSTOMER_INFORMATION: "MISSING CUSTOMER INFORMATION",
    BOOKING_CREATION_SERVICE_NOT_AVAILABLE: "THE SERVICE IS NOT AVAILABLE FOR BOOKING",
    BOOKING_CREATION_BOOKING_START_DATE_INVALID: "THE BOOKING START DATE IS NOT VALID",
    BOOKING_CREATION_BOOKING_END_DATE_INVALID: "THE BOOKING END DATE IS NOT VALID",
    BOOKING_CREATION_BOOKING_OVERLAP_CONFLICTION: "THERE IS OVERLAP BOOKING HOUR",
    BOOKING_CREATE_COMMON_ERROR : 'FAIL TO CREATE A NEW BOOKING',
    BOOKING_CREATION_MISSING_STAFF_INFORMATION : 'MISSING STAFF INFORMATION',
    BOOKING_CREATION_STAFF_NOT_AVAILABLE : 'THE STAFF IS NOT AVAILABLE FOR BOOKING'

}