export const GuardError = {
    MISSING_AUTHENTICATION_ERROR: 'MISSING AUTHENTICATION HEADER',
    MISSING_TOKEN_ERROR: 'MISSING TOKEN INFORMATION',
    WRONG_ACCESS_TOKEN_INFORMATION: 'INVALID TOKEN',
    MISSING_REFRESH_TOKEN_ERROR: 'MISSING refreshToken IN THE REQUEST COOKIE',
    MISSING_ACCESS_TOKEN_ERROR: 'MISSING accessToken IN THE REQUEST COOKIE',
    WRONG_REFRESH_TOKEN_INFORMATION: 'INVALID REFRESH TOKEN',
    TOKEN_IS_EXPIRED: 'TOKEN IS EXPIRED',
    REFRESH_TOKEN_IS_EXPIRED: 'refreshToken IS EXPIRED',
    MISSING_RESET_TOKEN_INFORMATION: 'MISSING resettoken IN THE REQUEST HEADER',
    WRONG_RESET_TOKEN_INFORMATION: 'INVALID RESET TOKEN'
}